spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cafe
    username: root
    password: {cipher : faca0752f6b8ac9c3c603856d83eab245841aed17542dea183e3a9bbe5ad1237}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:mysql://127.0.0.1:3306/cafe
    user: root
    password:  {cipher : faca0752f6b8ac9c3c603856d83eab245841aed17542dea183e3a9bbe5ad1237}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka