server:
  port: 8070
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
  server:
      waitTimeInMsWhenSyncEmpty: 0