spring:
  application:
    name: config-server
  profiles:
    active:
    - native #, git, vault
  cloud:
    config:
      server:
        vault:
          port: 8200
          host: 127.0.0.1
          kv-version: 2
          backend: cafe-service
          profile-separator: /
        encrypt:
          enabled: true
server:
  port: 8071

encrypt:
  key: mysecretkey